"use strict";

const lines_levels = [
  [
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, true, false, "d"],
      [false, true, true, false, "c"],
      [false, false, false, true, "d"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, true, true, false, "c"],
      [true, true, true, true, "s"],
      [true, false, false, true, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, true, false, false, "d"],
      [true, false, false, true, "c"],
      [true, false, true, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [true, false, false, false, "d"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
  ],
  [
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, true, true, false, "c"],
      [false, true, true, true, "c"],
      [false, true, false, true, "c"],
      [false, false, true, true, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [true, false, false, false, "d"],
      [true, false, true, false, "c"],
      [false, true, false, false, "d"],
      [true, false, true, true, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, true, false, false, "d"],
      [true, false, false, true, "s"],
      [false, false, false, false, "c"],
      [true, false, false, false, "d"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
  ],
  [
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, true, true, false, "c"],
      [false, true, false, true, "c"],
      [false, true, true, true, "c"],
      [false, true, false, true, "c"],
      [false, false, true, true, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [true, true, true, false, "s"],
      [false, false, false, true, "d"],
      [true, false, false, false, "d"],
      [false, true, false, false, "d"],
      [true, false, true, true, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [true, true, false, false, "c"],
      [false, true, false, true, "c"],
      [false, true, false, true, "c"],
      [false, false, false, true, "d"],
      [true, false, true, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, true, false, "d"],
      [false, false, true, false, "d"],
      [false, true, true, false, "c"],
      [true, false, false, true, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [true, true, false, false, "c"],
      [true, true, false, true, "c"],
      [true, false, false, true, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
    [
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
      [false, false, false, false, "c"],
    ],
  ],
];
